eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka
    register-with-eureka: true #true的话自身也作为一个客户端
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka
#server:
#  port: 8761
#management:
#  context-path: /
